### ISSUE TITLE
Add support for cypress

### ISSUE THREAD

**Issue by gracegeng88** [harled/rails-docker#13]
`apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb`

**Comment by krsyoung** [comment]
@gracegeng88 think we should include this in the current `run` image or should we make a new `test` image set?

**Comment by gracegeng88** [comment]
@krsyoung new `test` image sounds good 👍

**Comment by krsyoung** [comment]
Awesome, thanks @gracegeng88!
