### ISSUE TITLE
Image for Ruby 3.3.1

### ISSUE THREAD

**Issue by jonathanloos** [harled/rails-docker#43]
Hello! We love these images and are in the process of upgrading to Ruby 3.3.1 and would like to see the newest version supported.

The work here would involve the updating of the rails-build and rails-run pipelines to each support ruby 3.3.1.

**Comment by jonathanloos** [comment]
I forked this repo and will work on a PR in the coming days.

**Comment by krsyoung** [comment]
Closed via https://github.com/harled/rails-docker/pull/44. 🙇
