### ISSUE TITLE
Upgrade to Ruby 3.3.2, 3.3.3 and 3.3.4.

### ISSUE THREAD

**Issue by jonathanloos** [harled/rails-docker#50]
Hey @krsyoung !

I'd like to propose the introduction of new ruby versions to this repository. There's a couple gaps in it so I'd like to push 3.3.2, 3.3.3 and 3.3.4 out. Note that we are now hosting our own images so pushing to your `krsyoung` docker account can be done for QA, but we are no longer reliant on it (we still use this repo though).

I'll submit the PR shortly, let me know if you have questions, comments or concerns!

**Comment by krsyoung** [comment]
Thanks @jonathanloos. Curious, is the `anony-base` image being used any more? If not, I'll likely sunset that from this repo / the build scripts.

**Comment by jonathanloos** [comment]
> Thanks @jonathanloos. Curious, is the `anony-base` image being used any more? If not, I'll likely sunset that from this repo / the build scripts.

Nope we are not using it anymore!

**Comment by krsyoung** [comment]
Final updates applied and new strategy set. Full details: https://github.com/harled/rails-docker/issues/53

Going forward only a (new) rails-dev image will be supported for local devcontainer / docker-compose development. The other images are archived favouring more modern solutions.
